- hosts: all
  become: yes
  vars:
    sudoers:
      - user01
  tasks:
    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        append: yes
      with_items: "{{ sudoers }}"
    - name: Set authorized_keys in alternate location
      authorized_key:
        user: "{{ item }}"
        state: present
        key: '{{ lookup("file", "./{{ item }}.pub" ) }}'
        manage_dir: False
      with_items: "{{ sudoers }}"
    - name: Add sudoer permission with no-password
      shell: |
        echo  '{{ item }} ALL=(ALL) NOPASSWD:ALL' >/etc/sudoers.d/"{{ item }}"
      with_items: "{{ sudoers }}"
